#properties > yml > yaml
server:
#    port:
    port: 8089


mybatis:
#    mapper-locations: classpath:mapper/*Mapper.xml
#    type-aliases-package: com.spring.project.Entity

#    <context:component-scan base-package="com.XXX"></context:component-scan>
context:
    component-scan base-package: "com.ApplicationContextUtils"

spring:
    datasource:
#        url: jdbc:mysql://121.5.111.133:3306/mybatis_plus?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&allowPublicKeyRetrieval=true
#        type: com.alibaba.druid.pool.DruidDataSource    \u963F\u91CCdruid\u6570\u636E\u5E93\u8FDE\u63A5\u6C60
        #driver-class-name: org.gjt.mm.mysql.Driver
#        url: jdbc:mysql://121.5.111.133:3306/power?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
        url: jdbc:mysql://127.0.0.1:3306/mybatis_plus?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
#        password: a807a807a807
        password:

